sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: cUytcK1dNT0qS8aeYZ6P6L8UExQ4980b9/0rJZq+zpzfwDbTgdnb9mHjyEJWxfPGxU2I8YSS7GylKuwKQKEZ+kDkgXfipxHGbjxIo3dqYG2MuAoz7OwadsN6Yk/Vfa0c4k/araUVBT+0oh0MCILxFx8SFEgAQMVW7tz51zI5qpM=
  email:
    recipients:
      secure: I/V+eKMOrcY2ZNi5n9lee05oydfuu7WEyeEA5o5uV+L/ZsggNat6HWYt3yIeEdo6qfi1X890eFMLtyErikxBn2qT/vS4lyRCkT6qI1lRRTn+VbPUUJ+rcLLgH/mHa2jfg3CIg9kT5sbdfu2JVniksXCpS1onsX4IFQfeK2hdQUM=
